version: "3.6"
services:
  web:
    container_name: react_bff 
    restart: always
    build: .
    ports:
        - "3000:3000"
    tty: true
    volumes:
        - .:/usr/src/app
    environment:
      NODE_ENV: production 
